################################
# 🦎 KOMODO COMPOSE - SECURE 🦎 #
################################

services:
  mongo:
    container_name: mongo
    image: mongo
    labels:
      komodo.skip:
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    networks:
     - komodo
    secrets:
      - komodo_db_username
      - komodo_db_password
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/komodo_db_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/komodo_db_password

  core:
    container_name: komodo_core
    user: 1000:1000
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    restart: unless-stopped
    depends_on:
      - mongo
    secrets:
      - komodo_db_username
      - komodo_db_password
      - komodo_passkey
      - komodo_webhook
      - komodo_jwt
    networks:
      - proxy
      - komodo
    labels:
      - "komodo.skip:"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.komodo.entrypoints=http"
      - "traefik.http.routers.komodo.rule=Host(`$KOMODO_HOST`)"
      - "traefik.http.middlewares.komodo-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.komodo.middlewares=it-tools-https-redirect"
      - "traefik.http.routers.komodo-secure.entrypoints=https"
      - "traefik.http.routers.komodo-secure.rule=Host(`$KOMODO_HOST`)"
      - "traefik.http.routers.komodo-secure.tls=true"
      - "traefik.http.routers.komodo-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.komodo-secure.service=komodo_core"
      - "traefik.http.services.komodo_core.loadbalancer.server.port=9120"
    env_file: ./compose.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME_FILE: /run/secrets/komodo_db_username
      KOMODO_DATABASE_PASSWORD_FILE: /run/secrets/komodo_db_password
      KOMODO_PASSKEY_FILE: /run/secrets/komodo_passkey
      KOMODO_WEBHOOK_SECRET_FILE: /run/secrets/komodo_webhook
      KOMODO_JWT_SECRET_FILE: /run/secrets/komodo_jwt
    volumes:
      - ./data/repo-cache:/repo-cache
      - ./data/syncs:/syncs
      - /etc/localtime:/etc/localtime:ro

  periphery:
    container_name: komodo_periphery
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
        USER 1000:1000
        WORKDIR /home/<USER>
        ENV HOME=/home/<USER>
    user: 1000:1000
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    networks:
      - komodo
    labels:
      komodo.skip:
    restart: unless-stopped
    env_file: ./compose.env
    secrets:
      - komodo_passkey
    depends_on:
      - socket-proxy
    environment:
      # THE KEY to making periphery access docker without docker.sock
      DOCKER_HOST: tcp://socket-proxy:2375
      PERIPHERY_PASSKEYS_FILE: /run/secrets/komodo_passkey
    volumes:
      - /proc:/proc
      - /home/<USER>/docker:/home/<USER>/docker
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    environment:
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
      - AUTH=1 #optional, enable for pushing builds to registry and increasing pull rate limits
      - BUILD=1 #required to build images
      - COMMIT=0 #optional
      - CONFIGS=0
      - CONTAINERS=1 #required to manage containers
      - DISABLE_IPV6=0
      - DISTRIBUTION=1 #required for image digest and registry info
      - EVENTS=1 #required for core communication
      - EXEC=1 #required for 'exec' into container, future use
      - IMAGES=1 #required to manage images
      - INFO=1
      - NETWORKS=1 #required to manage networks
      - NODES=0
      - PING=1 #required for core communication
      - POST=1 #required for WRITE operations to all other permissions
      - PLUGINS=0 #optional
      - SECRETS=1
      - SERVICES=1 # for future swarm
      - SESSION=0
      - SWARM=1 # for future swarm
      - SYSTEM=1 #optional, enable for system stats in dashboard
      - TASKS=0
      - VERSION=1 #required for core communication
      - VOLUMES=1 #required to manage volumes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - komodo
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run

volumes:
  mongo-data:
  mongo-config:
  repo-cache:

secrets:
  komodo_db_username:
    file: ./data/secrets/komodo_db_username.secret
  komodo_db_password:
    file: ./data/secrets/komodo_db_password.secret
  komodo_passkey:
    file: ./data/secrets/komodo_passkey.secret
  komodo_webhook:
    file: ./data/secrets/komodo_webhook.secret
  komodo_jwt:
    file: ./data/secrets/komodo_jwt.secret
networks:
  proxy:
    external: true
  komodo: {}
